### ISSUE TITLE
How to correctly pass docker environment variables

### ISSUE THREAD

**Issue by dannykorpan** [Frooodle/Stirling-PDF#333]
Hi,

how do I correctly pass environment variables for e.g. the default language in a docker compose file?
Here is my docker compose, but the language is still English and not German. What is wrong here?

```
version: '3.3'
services:
    s-pdf:
      restart: always
      container_name: pdftools
      labels:
        - "com.centurylinklabs.watchtower.enable=true"
      image: frooodle/s-pdf
      volumes:
        - /opt/docker/pdftools/tessdata:/usr/share/tesseract-ocr/4.00/tessdata
      networks:
        - default
      environment:
        - defaultLocale="de-DE"
        - googlevisibility="false"

networks:
  default:
    name: www
    external: true
```

Thank you for any help in advance
Danny
