### ISSUE TITLE
No login page

### ISSUE THREAD

**Issue by ontheair81** [Frooodle/Stirling-PDF#526]
Running `frooodle/s-pdf:0.16.1-lite` behind nginx reverse proxy on Debian 12.4 via docker. No extraConfigs and no manual changes to settings.yml have been made.

It runs fine, just there is no login page.
Here is my compose file:

```
version: '3.3'

services:
  stirling-pdf:
    container_name: pdf_mydomain_tld
    image: frooodle/s-pdf:0.16.1-lite
    ports:
      - ':8080'
    volumes:
      - /home/user/bind-mounts/stirling-pdf/trainingData:/usr/share/tesseract-ocr/5/tessdata
      - /home/user/bind-mounts/stirling-pdf/extraConfigs:/configs
      - /home/user/bind-mounts/stirling-pdf/customFiles:/customFiles/
    environment:
      - VIRTUAL_HOST=pdf.mydomain.tld
      - LETSENCRYPT_HOST=pdf.mydomain.tld
      - DOCKER_ENABLE_SECURITY=true
      - SECURITY_ENABLE_LOGIN=true
      - SYSTEM_DEFAULT_LOCALE=de-DE
      - SYSTEM_GOOGLE_VISIBILITY=false
    networks:
      - net
    restart: always

networks:
  net:
    external: true
```
What am I doing wrong?
Any help is very appreciated, thank you!
