### ISSUE TITLE
0.17.1-lite: Container not starting

### ISSUE THREAD

**Issue by ontheair81** [Frooodle/Stirling-PDF#531]
Running `frooodle/s-pdf:0.17.1-lite` via Docker on Debian 12.4. The container is not able to start with this error message:

`Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/scripts/init.sh": stat /scripts/init.sh: no such file or directory: unknown`

The non-lite version works as expected.

If needed, here is my compose:

```
version: '3.3'

services:
  stirling-pdf:
    container_name: pdf_mydomain_tld
    image: frooodle/s-pdf:0.17.1-lite
    ports:
      - ':8080'
    volumes:
      - /home/user/bind-mounts/stirling-pdf/trainingData:/usr/share/tesseract-ocr/5/tessdata
      - /home/user/bind-mounts/stirling-pdf/extraConfigs:/configs
      - /home/user/bind-mounts/stirling-pdf/customFiles:/customFiles/
    environment:
      - VIRTUAL_HOST=pdf.mydomain.tld
      - LETSENCRYPT_HOST=pdf.mydomain.tld
      - DOCKER_ENABLE_SECURITY=true
      - SECURITY_ENABLE_LOGIN=true
      - SYSTEM_DEFAULT_LOCALE=de-DE
      - SYSTEM_GOOGLE_VISIBILITY=false
    networks:
      - net
    restart: always

networks:
  net:
    external: true
```
